apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-marketplace
  namespace: argocd
  labels:
    purpose: marketplace-iam
spec:
  destination:
    namespace: marketplace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ionos/marketplace_sbx/iam/keycloak
    repoURL: https://github.com/bialask-daiteap/dome-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true