apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-trust
  namespace: argocd
  labels:
    purpose: trust-anchor
spec:
  destination:
    namespace: dome-trust
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ionos/dome-trust_sbx/portal
    repoURL: https://github.com/bialask-daiteap/dome-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true